name: Dart CI

on:
  push:
    branches: 
    - '*'
  pull_request:
    branches: 
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: test ci/cd pipeline
      run: echo "test" 
